### ISSUE TITLE
Replace autocomplete for contacts

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#179]
We use an autocomplete to select who to send an email to. It doesn't work great atm.

This seems to work well:
https://shadcn-tag-input.vercel.app/

**Comment by codingsagar** [comment]
![image](https://github.com/elie222/inbox-zero/assets/68506265/04304946-a00b-4d7f-9b78-4ae3b97fefcb)

Just want to confirm we want something like this so that we can send email to multiple people?

![image](https://github.com/elie222/inbox-zero/assets/68506265/84732e03-db1f-48c3-9119-a34e6d5be1be)

And the new message modal also hides behind the left navigation menu. Do we have to use this new input instead of that To label input box ? Because that does not seem to work.

**Comment by elie222** [comment]
Regarding 1, yes. It also uses contact autocomplete. So just something to keep in mind.
Regarding 2, that's a but that shouldn't be happening. Can create a new issue for that.

**Comment by kubra16** [comment]
I would like to work on this issue.

**Comment by elie222** [comment]
> I would like to work on this issue.

I've assigned you to it! Feel free to connect on Discord DM if you need help / want to chat more about it. Or following up here is fine too.

**Comment by kubra16** [comment]
![Screenshot 2024-05-28 160536](https://github.com/elie222/inbox-zero/assets/110725429/22ae33fe-2b17-41df-81b0-5807d52fa66e)
I have made similar changes, where user can add multiple emails and can also delete when clicking on the icon. This is how it should be ? Let me know if you want any changes.

**Comment by prynsh** [comment]
hey @kubra16  can I help?

**Comment by elie222** [comment]
Hey, I don't remember the state of this one. For the screenshot I'm not in love with the design of it. Also the modal being so narrow.

**Comment by MaYaNkKashyap681** [comment]
Is @kubra16 or anyone else is still working on this issue?

**Comment by elie222** [comment]
> Is @kubra16 or anyone else is still working on this issue?

You can take it if you like

**Comment by mittalsam98** [comment]
Hey @elie222 can you assign this to me pls
